import { Montserrat } from "next/font/google";
import "../app/styles/globals.scss";
// import type { NextFont } from "next/dist/compiled/@next/font";

const montserrat = Montserrat({ subsets: ["latin"] });

// const roboto : NextFont = Roboto({
//   weight: ['400','500','700','900'],
//   subsets: ['latin'],
//   display: 'swap',
// })

export const metadata = {
  title: "Rogue Dev Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
